name: Scale Test

on:
  # TODO: Remove from pull request, keep after Build Images
  # This is a test
  pull_request:
    branches: [main]
  # TODO: Test execution after 'Build Images' workflow
  # workflow_run:
    # workflows: [Build Images]
    # types:
      # - completed
  workflow_dispatch:
    inputs:
      num_deployments:
        description: "Number of Traffic Deployments"
        default: 1000
        type: number
      num_replicas:
        description: "Number of Traffic Replicas per Deployment"
        default: 40
        type: number
      num_netpol: 
        description: "Number of Network Policies"
        default: 1000
        type: number
      num_unique_labels_per_pod: 
        description: "Number of Unique Labels per Pod"
        default: 2
        type: number
      num_unique_labels_per_deployment:
        description: "Number of Unique Labels per Deployment"
        default: 2
        type: number
      num_shared_labels_per_pod:
        description: "Number of Shared Labels per Pod"
        default: 3
        type: number
      delete_labels: 
        description: "Delete Labels"
        default: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  scale-test:
    # if: ${{ github.event_name == 'merge_group' }}
    name: Scale Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version-file: go.mod
      # - run: go version
      #
      # - name: Az CLI login
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Run Scale Test
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
        shell: bash
        run: |
          set -euo pipefail
          echo "I'm Running"
          echo "Deployments: ${{ inputs.num_deployments }}"
          echo "Replicas: ${{ inputs.num_replicas }}"
          echo "NetPol: ${{ inputs.num_netpol }}"
          echo "Unique labels pods: ${{ inputs.num_unique_labels_per_pod }}"
          echo "Unique shared label pods: ${{ inputs.num_shared_labels_per_pod }}"
          echo "Unique labels deployments: ${{ inputs.num_unique_labels_per_deployment }}"
          echo "Delete Labels? ${{ inputs.delete_labels }}"
          # go test -v ./test/e2e/. -timeout 300m -tags=scale -count=1  -args -image-tag=$(make version) -image-registry=${{vars.ACR_NAME}} -image-namespace=${{github.repository}}
